stages:
  - build
  - tests

build-test:
  stage: build
  image: debian:bullseye
  script:
    - apt-get update && apt-get -y install build-essential libreadline-dev
    - make tesh

unit-test:
  stage: tests
  image: debian:bullseye
  script:
    - apt-get update && apt-get -y install build-essential libreadline-dev
    - make test
    - ./test

test-script:
  stage: tests
  image: debian:bullseye
  script:
    - apt-get update && apt-get -y install build-essential libreadline-dev
    - chmod +x ./tests/tester.sh
    - INDOCKER=1 ./tests/tester.sh
