name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: debian:bullseye

    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: apt-get update && apt-get -y install build-essential libreadline-dev
    - name: Building tests
      run: make test
    - name: Running tests
      run : ./test
    - name: Running tesh-tester
      run: chmod +x ./tests/tester.sh && INDOCKER=1 ./tests/tester.sh
